name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for opening the issue! The developers will look in to it and respond shortly.'
        pr-message: 'Thank you for contributing! Make sure that your changes have been tested locally or on Github Pages in a seperate repo.'
